### ISSUE TITLE
Provided dependencies

### ISSUE THREAD

**Issue by Philippus** [scalacenter/sbt-version-policy#82] opened 2021-05-14 21:00 UTC
I've got a project with a dependency that's marked as `Provided`. Running `versionPolicyReportDependencyIssues` will report missing dependencies because it only checks the `Compile` scope. Is this by design?

**Comment by julienrf** [comment] 2021-05-15 08:21
No, that’s not expected. Could you please provide a test case with the expected behavior in https://github.com/scalacenter/sbt-version-policy/tree/main/sbt-version-policy/src/sbt-test/sbt-version-policy?

**Comment by Philippus** [comment] 2021-05-15 11:46
I'm having trouble getting a failing test using `publishLocal`, but here's the example: https://github.com/Philippus/sbt-version-policy/tree/reproduce-issue-82.

**Comment by julienrf** [comment] 2021-05-17 09:58
Running `scripted sbt-version-policy/provided` in your branch works for me. Which command should I run to reproduce the issue?

**Comment by Philippus** [comment] 2021-05-17 10:10
I'm getting the following:
```
[info] [error] Incompatibilities with nl.gn0s1s:pureconfig-javanet:0.0.1
[info] [error]   com.chuusai:shapeless_2.13: missing dependency
[info] [error]   com.github.pureconfig:pureconfig-core_2.13: missing dependency
[info] [error]   com.github.pureconfig:pureconfig-generic-base_2.13: missing dependency
[info] [error]   com.github.pureconfig:pureconfig-generic_2.13: missing dependency
[info] [error]   com.github.pureconfig:pureconfig-macros_2.13: missing dependency
[info] [error]   com.github.pureconfig:pureconfig_2.13: missing dependency
[info] [error]   com.typesafe:config: missing dependency
[info] [error] java.lang.Exception: Compatibility check failed (see messages above)
[info] [error]  at sbtversionpolicy.SbtVersionPolicySettings$.$anonfun$findIssuesSettings$8(SbtVersionPolicySettings.scala:223)
[info] [error]  at sbtversionpolicy.SbtVersionPolicySettings$.$anonfun$findIssuesSettings$8$adapted(SbtVersionPolicySettings.scala:193)
[info] [error]  at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[info] [error]  at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[info] [error]  at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[info] [error]  at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[info] [error]  at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[info] [error]  at sbt.Execute.work(Execute.scala:291)
[info] [error]  at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[info] [error]  at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[info] [error]  at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[info] [error]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [error]  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info] [error]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [error]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info] [error]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info] [error]  at java.lang.Thread.run(Thread.java:748)
[info] [error] (versionPolicyReportDependencyIssues) java.lang.Exception: Compatibility check failed (see messages above)
[info] [error] Total time: 1 s, completed 17-mei-2021 12:08:45
[error] x sbt-version-policy/provided 
```

**Comment by Philippus** [comment] 2021-05-17 10:21
Ah, I think I know what happened. I think I had a 0.0.1 version locally published where pureconfig was still in the compile-scope. After removing that version the test now works.
Sorry to bother you.

**Comment by julienrf** [comment] 2021-05-17 10:43
No worries! Should we close the issue?

**Closed** 2021-05-17 11:02 UTC
